version: '3'
services:
  api:
    image: demontiecosta/teste_pratico:1.0
    container_name: testePratico
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
      - ./default:/etc/nginx/sites-available/default
    ports:
      - 9008:80
    restart: always
    stdin_open: true
    tty: true
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: testePratico

